wandi_easy_admin_plus_login:
    path: /login
    defaults:
        _controller: AkrzemEasyAdminPlusBundle:Admin:login

wandi_easy_admin_plus_logout:
    path: /logout

wandi_easy_admin_plus_translations:
    path: /translations
    defaults:
        _controller: AkrzemEasyAdminPlusBundle:Admin:translations
